// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {object} from '../models';
import {context} from '../models';

export function CheckIsServerRunning():Promise<boolean>;

export function GitHeadCommit(arg1:string):Promise<object.Commit>;

export function GitLatestCommit(arg1:string):Promise<void>;

export function GitPull(arg1:string):Promise<string>;

export function GitStatus(arg1:string):Promise<Array<object.Commit>>;

export function StartServer(arg1:string):Promise<boolean>;

export function StartUp(arg1:context.Context):Promise<void>;

export function StopServer():Promise<boolean>;
