// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckIsServerRunning() {
  return window['go']['comfyUI']['ComfyUI']['CheckIsServerRunning']();
}

export function GitHeadCommit() {
  return window['go']['comfyUI']['ComfyUI']['GitHeadCommit']();
}

export function GitLatestCommit() {
  return window['go']['comfyUI']['ComfyUI']['GitLatestCommit']();
}

export function GitPull() {
  return window['go']['comfyUI']['ComfyUI']['GitPull']();
}

export function GitStatus() {
  return window['go']['comfyUI']['ComfyUI']['GitStatus']();
}

export function Shutdown() {
  return window['go']['comfyUI']['ComfyUI']['Shutdown']();
}

export function StartServer() {
  return window['go']['comfyUI']['ComfyUI']['StartServer']();
}

export function StartUp(arg1) {
  return window['go']['comfyUI']['ComfyUI']['StartUp'](arg1);
}

export function StopServer() {
  return window['go']['comfyUI']['ComfyUI']['StopServer']();
}

export function StoreOutput(arg1, arg2) {
  return window['go']['comfyUI']['ComfyUI']['StoreOutput'](arg1, arg2);
}
