// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckIsServerRunning() {
  return window['go']['comfyUI']['ComfyUI']['CheckIsServerRunning']();
}

export function GitHeadCommit(arg1) {
  return window['go']['comfyUI']['ComfyUI']['GitHeadCommit'](arg1);
}

export function GitLatestCommit(arg1) {
  return window['go']['comfyUI']['ComfyUI']['GitLatestCommit'](arg1);
}

export function GitPull(arg1) {
  return window['go']['comfyUI']['ComfyUI']['GitPull'](arg1);
}

export function GitStatus(arg1) {
  return window['go']['comfyUI']['ComfyUI']['GitStatus'](arg1);
}

export function StartServer(arg1) {
  return window['go']['comfyUI']['ComfyUI']['StartServer'](arg1);
}

export function StartUp(arg1) {
  return window['go']['comfyUI']['ComfyUI']['StartUp'](arg1);
}

export function StopServer() {
  return window['go']['comfyUI']['ComfyUI']['StopServer']();
}
