// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Confirm(arg1, arg2) {
  return window['go']['backend']['App']['Confirm'](arg1, arg2);
}

export function GetComfyUIPath() {
  return window['go']['backend']['App']['GetComfyUIPath']();
}

export function Login(arg1) {
  return window['go']['backend']['App']['Login'](arg1);
}

export function Logout() {
  return window['go']['backend']['App']['Logout']();
}

export function OpenFileInDir(arg1, arg2) {
  return window['go']['backend']['App']['OpenFileInDir'](arg1, arg2);
}

export function OpenFolder() {
  return window['go']['backend']['App']['OpenFolder']();
}

export function Prompt(arg1, arg2) {
  return window['go']['backend']['App']['Prompt'](arg1, arg2);
}

export function SaveFile(arg1, arg2) {
  return window['go']['backend']['App']['SaveFile'](arg1, arg2);
}

export function SelectFolder(arg1) {
  return window['go']['backend']['App']['SelectFolder'](arg1);
}

export function Startup(arg1) {
  return window['go']['backend']['App']['Startup'](arg1);
}
