// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function Confirm(arg1:string,arg2:string):Promise<string>;

export function GetComfyUIPath():Promise<string>;

export function Prompt(arg1:string,arg2:string):Promise<string>;

export function SaveFile(arg1:string,arg2:string):Promise<void>;

export function SelectFolder(arg1:string):Promise<string>;

export function SetComfyUIPath(arg1:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
