// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetModelFileSHA256(arg1) {
  return window['go']['models']['Service']['GetModelFileSHA256'](arg1);
}

export function ListModelDir(arg1) {
  return window['go']['models']['Service']['ListModelDir'](arg1);
}

export function StartUp(arg1) {
  return window['go']['models']['Service']['StartUp'](arg1);
}
