// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {context} from '../models';

export function GetModelFileSHA256(arg1:string):Promise<string>;

export function ListModelDir():Promise<models.Dir>;

export function StartUp(arg1:context.Context):Promise<void>;
