// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Confirm(arg1, arg2) {
  return window['go']['main']['App']['Confirm'](arg1, arg2);
}

export function Prompt(arg1, arg2) {
  return window['go']['main']['App']['Prompt'](arg1, arg2);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function SelectFolder(arg1) {
  return window['go']['main']['App']['SelectFolder'](arg1);
}

export function SetComfyUIPath() {
  return window['go']['main']['App']['SetComfyUIPath']();
}
